name: linker
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  badges: ^3.0.3
  blur: ^3.1.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  dio: ^5.1.1
  dotted_border: ^2.0.0+3
  dotted_line: ^3.1.0
  ##easy_localization: ^3.0.1
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  flutter_local_notifications: ^14.1.1
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.7.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.4
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.3
  image_picker: ^0.8.7+1
  intl_phone_field: ^3.1.0
  like_button: ^2.0.5
  modal_bottom_sheet: ^2.1.2
  percent_indicator: ^4.2.3
  photo_view: ^0.14.0
  pin_code_fields: ^7.4.0
  provider: ^6.0.5
  readmore: ^2.2.0
  shared_preferences: ^2.1.0
  shimmer: ^2.0.0
  signed_spacing_flex: ^1.0.0
  story_view: ^0.14.0
  syncfusion_flutter_sliders: ^21.1.37
  url_launcher: ^6.1.10
  image_cropper: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/newappicon.png"
  remove_alpha_ios: true

flutter:
  fonts:
    - family: SFArabic
      fonts:
        - asset: assets/fonts/SFArabic-Regular.ttf

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/translations/
